### ISSUE TITLE
Support for Array fields

### ISSUE THREAD

**Issue by jwoertink** [luckyframework/avram#147]
Postgres supports [array data types](https://www.postgresql.org/docs/10/arrays.html). These come with special querying syntax, and implementation. I think we can start with single dimensional arrays first which would look like

```crystal
column items : Array(String)
column ticks : Array(Int32)
```

A multidimensional may get tricky since postgres seems to allow for any number of nested arrays as long as they're all the same type. So I think `text[][][][][]` would be allow 😝  I have no idea how that would map to crystal cleanly, but also super edge case that could come later.

**Comment by paulcsmith** [comment]
Yeah definitely single dimension first and multi-dimension maybe never haha. I think the migration side of this could be pretty easy, not sure what it'd take to get this working in the rest of Lucky. Particularly how would param parsing work for this. That could get tricky to handle. JSON is easy but url form encoded has no standard for this 😬

Maybe we don't even try for url form encoded and just always treat what you pass in as a single array item and leave it up to the user to figure out what they want to do with it:

```
```

**Comment by jwoertink** [comment]
I know there was a [PR in crystal](https://github.com/crystal-lang/crystal/pull/7862) to handle some array stuff. Not sure if that will matter or not for us. I'm gonna start with the migration and model setup stuff first since I have an immediate need for that. I'll think about the operation stuff while I'm digging around in there and see what I can come up with.

**Comment by paulcsmith** [comment]
In order to add a new type you need to tell Avram how to parse it. That’s the main reason I brought it up. But maybe you can do some parsing that’s just returns a wrapped string to get it working. 

For migrations I think you can add another argument to the base column  https://github.com/luckyframework/avram/blob/master/src/avram/migrator/columns/base.cr called “@array”

Then if array is present it adds “[]” to the generated statement to make it an array. 

Lmk if you need any help with this
