### ISSUE TITLE
Add built-in EmailAttr type

### ISSUE THREAD

**Issue by paulcsmith** [luckyframework/avram#16]
Validate valid email, downcase, etc.

Similar to:

* https://github.com/luckyframework/lucky_record/blob/1c0757fa6686d6687259e5b8c299a61e1d4815de/spec/model_spec.cr#L7
* https://github.com/luckyframework/lucky_record/blob/b7658340546171e783527af643e43e6b0426dc98/spec/support/custom_email.cr#L1
* Validation should be added in the `parse` method and use `FailedCast` if it is not in a valid format.

**Comment by jwoertink** [comment]
We now support case insensitive String columns which are default for the User model on email column that we ship with Lucky. As for email validations, those are beyond difficult to get 100% right. Check out the [Ruby example](https://emailregex.com/).... If you get real close, squint your eyes, and slowly move backwards you may see a picture of a dolphin riding a jetski.

Instead of a specific Email type, we just need to focus on custom types in general https://github.com/luckyframework/avram/issues/497
