### ISSUE TITLE
Aggregate methods bork subsequent queries

### ISSUE THREAD

**Issue by jwoertink** [luckyframework/avram#194]
If you do a `select_count` on a query, and then use that same query to do something right after, the query will most likely fail (exceptions apply).

```crystal
query = UserQuery.new.where_tasks(TaskQuery.new.completed(true))
puts query.select_count

# This line fails with PG error:
# ERROR:  column "user.id" must appear in the GROUP BY clause or be used in an aggregate function
query.first
```

This is because in the `query.first`, the SQL is now

```
SELECT COUNT(*)
FROM users
INNER JOIN tasks ON users.id = tasks.user_id
ORDER BY users.id ASC
LIMIT 1
```

It looks like [this line](https://github.com/luckyframework/avram/blob/master/src/avram/query_builder.cr#L178-L179) is the main cause since it resets the selections

**Comment by paulcsmith** [comment]
I think the *root* issue is that we are mutating the query builder instead of returning a new modified version of the query. This could lead to other bugs too where you modify a query in one part of the   program and in another part  it  is also unexpectedly modified.

This makes me wonder if we need to  use a  `struct` or just return a new query builder with  each change  so that we  always  have new  objects. We may need to experiment bit  with this, but I think  we should  definitely  move in the direction of  returning new objects  to  avoid these kinds of issues
