### ISSUE TITLE
`created_at` and `updated_at` aren't populated by `MyModel::SaveOperation` when `default_columns` doesn't have `timestamps`

### ISSUE THREAD

**Issue by lesderid** [luckyframework/avram#315]
`created_at` and `updated_at` aren't populated by `MyModel::SaveOperation` when the base model's `default_columns` doesn't have `timestamps`.

I have a `BaseModel` that overrides the `default_columns` so it only has a primary key (and no timestamps). I explicitly add `created_at` and/or `updated_at` to *some* of my models.

For example, say `MyModel` inherits from `BaseModel` and has a `column created_at : Time`. When I use `MyModel::SaveOperation`, `created_at` doesn't get automatically populated and I have to add it manually with `created_at.value = Time.utc`. The column is definitely there however, because validation fails with saying "`created_at` is required" when I don't manually set `created_at.value`.

**Comment by paulcsmith** [comment]
Sounds like a bug, but it seems odd since I thought I tried this at some point and it worked.

Just to make sure I understand, you're saying you manually add `column created_at : Time` to some models, but that it isn't getting populated automatically even though the column is defined inside the `table` block?

**Comment by lesderid** [comment]
> Just to make sure I understand, you're saying you manually add `column created_at : Time` to some models, but that it isn't getting populated automatically even though the column is defined inside the `table` block?

Yep.

**Comment by paulcsmith** [comment]
I just saw your convo on Gitter. Left a fix there, but I'll post here as well: https://gitter.im/luckyframework/Lobby?at=5e64061847b424792531a477

Add `autogenerated: true` to created_at/updated_at columns if you add them separately. Or use `timestamps` if you need both. I'll leave this open though because I think we can make it so `autogenerated` is no longer necessary

**Comment by paulcsmith** [comment]
As mentioned in Gitter this actually is intended behavior, but I'll leave a comment here in case anyone stumbles on this through Google.

The reason we need to mark it `autogenerated: true` is so that Avram doesn't run `validate_required` on the column even though it is required. This is because we need to set the timestamps *right* before save, after all the validations have run.

So the "fix" is to document this in the guides. You really only need this option for created_at/updated_at so should probably go in the "customizing defaults" section

**Comment by lesderid** [comment]
Actually I think the current behaviour is correct (and this issue should be closed as invalid): there might be rare cases where you have a `created_at`/`updated_at` column that you don't want to be populated automatically. That would mean `SaveOperation.insert` should be changed to check for `autogenerated` in addition to just `responds_to?`, though.

**Comment by paulcsmith** [comment]
Good point! I hadn't thought of that, but that's true. Sometimes people use triggers to fill those in 👍
