### ISSUE TITLE
SaveOperation fails with blank permitted_columns

### ISSUE THREAD

**Issue by jwoertink** [luckyframework/avram#377]
Ref: https://gitter.im/luckyframework/Lobby?at=5ecc5bc8a91f120a6cc15952

Brain may be fried so I could have missed something, but I think this doesn't work:

```crystal
class Category < Avram::Model
  table do
    column color : String
    column budget : Int32?
  end
end

class SaveCategory < Category::SaveOperation
  permit_columns :color, :budget
end

params = Avram::Params.new({"category" => {"color" => "#fff", "budget" => ""}})
SaveCategory.create(params) do |operation, category|
  # category is nil here
  operation.errors[:buget] #=> "is invalid"
end
```

In this case, the column in both the migration and model were added as nilable. When the form is submitted, the param sends an empty string for the nilable column. 
The stack it takes is this:

* https://github.com/luckyframework/avram/blob/master/src/avram/needy_initializer_and_save_methods.cr#L177
* https://github.com/luckyframework/avram/blob/master/src/avram/needy_initializer_and_save_methods.cr#L218
* https://github.com/luckyframework/avram/blob/master/src/avram/save_operation.cr#L87
* https://github.com/luckyframework/avram/blob/master/src/avram/save_operation.cr#L133
* https://github.com/luckyframework/avram/blob/master/src/avram/charms/int32_extensions.cr#L16
* https://github.com/luckyframework/avram/blob/master/src/avram/save_operation.cr#L138

Since this all happens on initialization, the `budget` attribute is already set with an error before any `before_save` callbacks have happened. I'm sure I'm missing something here, so I've marked this as needing investigation for now...

/cc. @franciscoadasme

**Comment by paulcsmith** [comment]
@jwoertink I'm fairly certain the problem is here: https://github.com/luckyframework/avram/blob/42ce5b55ccc1becfd85c5b7a87aaf55ceeb98acc/src/avram/charms/int32_extensions.cr#L14-L28

The problem is that it tries to parse an empty string which then raises. So it's not that the field is "required" it's that it isn't an Int32. This may also be an issue in https://github.com/luckyframework/avram/blob/master/src/avram/charms/time_extensions.cr with nilable columns.

I think the fix is to only try parsing if the String value is not blank. If it is blank, `return `SuccessfulCast.new(nil)`. This way if the value is blank it won't mark the field as invalid

Does that make sense?
