### ISSUE TITLE
default is acting not like it suppose to

### ISSUE THREAD

**Issue by confact** [luckyframework/avram#390]
When I add a default value to a column, say a boolean it should use that if not set in operation.

Now operation fails as I haven't filled the column. So I still have to set the default value of `false` or similar. check https://github.com/kindmetrics/kindmetrics/blob/master/src/actions/sign_ups/create.cr#L5 for example.

If I set a default value I want it to be used if I don't fill it in, why even have one if not?

**Comment by diddeb** [comment]
Let me second what @confact's saying. I have triple checked the current guides and indeed, it seems as if defaults defined in migrations are not applied to the operation:

```
web          | 2020-06-17T20:01:31.687720Z  ERROR - lucky: 
web          | Could not save SaveExperiment.
web          | 
web          |   ▸ enabled: is required
web          |  (Avram::InvalidOperationError)
```

...where `enabled` should be `true` as defined in the migration. Is this truly a missing feature – or a defect?

**Comment by jwoertink** [comment]
Yeah, that makes sense. I'll take a look and see what's going on under the hood. Thanks for the report!

**Comment by diddeb** [comment]
Thank you for being so responsive. Let me know if there's anything I can help test!

**Comment by paulcsmith** [comment]
We chatted about this in Gitter. Since we don't read the database to get the columns, the default must be supplied in the mapping. What we'd like to do is make it so you can do `column enabled : Bool = true` and it will set the default value in operations. We also want to add a check to the SchemaEnforcer to check for defaults in the database that are not also set in the model!

This way it is clear what the default is in the code, and Lucky will help you find missing defaults in the SchemaEnforcer. If someone wants to work on this they can. Just be warned that the model and operations macros are pretty complex so it may not be a bit trickier than expected

**Comment by confact** [comment]
@jwoertink @paulcsmith thanks for looking it through. I sounded a bit angry in my message there. Probably a lot of other stuff around me that spread over to the message. Sorry about that!

I think that makes totally sense to do that. I am okay to set the mapping, it will not be overwhelmed and it is best for performance as well. 

Thanks once again!

**Comment by paulcsmith** [comment]
@confact No problem! I know you well enough to not take it negatively at all :) I think I read it as intended and I totally get it! Having it do "nothing" is a bit confusing so we should help users know what to do and let the default be set in the mapping. Thanks for opening the issue!
