### ISSUE TITLE
Can't assign a smaller integer to the attribute for a larger integer

### ISSUE THREAD

**Issue by BrucePerens** [luckyframework/avram#414]
```
reply_index.value = 1
                  ^----
Error: instantiating 'Avram::Attribute(Int64 | Nil)+#value=(Int32)'
```
Avram should allow a smaller integer to be assigned to the attribute for a larger integer without making the user cast it.

**Comment by jwoertink** [comment]
That should work. I'm surprised you got an error. You're running on the latest Crystal and everything, right? This might need some more investigation

**Comment by paulcsmith** [comment]
I agree this is odd behavior, but is not something Avram specific. As you can see in this https://play.crystal-lang.org/#/r/9cqh Crystal does not auto upcast. I would recommend opening an issue in the Crystal repo to see if it is possible to do auto upcast Int32 -> Int64

Going to go ahead and close this since changing it in Avram would require some special hacks for ints and make the codebase more complex. 

For anyone that sees this issue, the fix is to call `to_i64` on the value you are assigning

**Comment by BrucePerens** [comment]
The Crystal team is adding type promotion to the language.

**Comment by paulcsmith** [comment]
Awesome! :D
