### ISSUE TITLE
Migrator obscures stack trace of unhandled exceptions

### ISSUE THREAD

**Issue by digitalcora** [luckyframework/avram#422]
Trying to set up a Lucky project for the first time, I ran into a strange error that took quite a while to debug. Part of the difficulty was that it turned out Avram was suppressing the real stack trace of the error.

in https://github.com/luckyframework/avram/blob/63be781/src/avram/migrator/migrator.cr:

```crystal
module Avram::Migrator
  def self.run
    yield
  rescue e : PQ::PQError
    raise e.message.colorize(:red).to_s
  rescue e : Exception   # <=
    raise e.message.to_s # <=
  end
end
```

The marked lines catch all exceptions and re-raise them, with a stack trace pointing here instead of the original source. The purpose of these lines is unclear to me, and in fact once I deleted them from my project's copy of Avram in `lib`, I got a much better stack trace that allowed me to solve the problem.

If there would be no harm in doing so, maybe these lines could be removed?

**Comment by jwoertink** [comment]
Hey @digitalcora Welcome to Lucky! Sorry you ran in to some issues. Hopefully you got it all set now. 

That is a good call. Normally when we catch errors like that, it's because we can usually provide a better error message than the one provided by Crystal's default. In this case since we're just re-raising the same error, I'm not seeing any benefit to having it. My guess is that it would be ok to remove those. What are your thoughts @paulcsmith ?

**Comment by paulcsmith** [comment]
I think the original reason was to highlight the error in red. But if it makes the stacktrace worse then we should remove it :D Thanks for opening the issue @digitalcora!

**Comment by matthewmcgarvey** [comment]
These are also places I believe are obscuring problems during migrations:

https://github.com/luckyframework/avram/blob/1e6f4edd4d49c518c858ee9ecc277a3b963051eb/src/avram/migrator/runner.cr#L192-L193

https://github.com/luckyframework/avram/blob/1e6f4edd4d49c518c858ee9ecc277a3b963051eb/src/avram/migrator/migration.cr#L99-L108
