### ISSUE TITLE
Refactor SchemaEnforcer to avoid re-querying the database for each model

### ISSUE THREAD

**Issue by matthewmcgarvey** [luckyframework/avram#462]
Right now, `Avram::Model` includes `Avram::SchemaEnforcer` and then each model makes sql requests to check that its table name and listed columns exist. So, having 10 models ends up making 20 queries. Right now, this check only runs once when starting an app in development, but if the check [ever gets moved to a middleware](https://github.com/luckyframework/lucky/issues/1142) it would make the sql queries on every request. And, if we want wanted to add more types of database checks (warn if belongs_to relationship doesn't have a foreign key relationship set up for example) we would also have to add yet another sql query.

## Proposal

I propose that we update models to include a `Avram::SchemaEnforceable` module and that runs all the checks. We also add an `Avram::DatabaseInfo` class that is accessible from the class-level of every `Avram::Database`. That class would have many `Avram::DatabaseTable`'s and each of those would have many `Avram::DatabaseColumn`'s. Rather than the checks getting passed a database class and using it to make a query, they will be passed the `Avram::DatabaseInfo` and have rich classes to compare to. The `Avram::DatabaseInfo` class should only run one query to get all the database tables and could also join to get the column info first or subsequent queries could be made (lazily or not). This `Avram::DatabaseInfo` should be a singleton so that it is only "new-ed" up once at application start.

I expect this to make adding database view support to the schema enforcement process easier than it would be right now.

### Pseudo-Code

```crystal
class Avram::Model
  include Avram::SchemaEnforceable
  ...
end

module Avram::SchemaEnforceable
  DATABASE_VALIDATIONS = [
    EnsureExistingTable,
    EnsureMatchingColumns
  ]
  DATABASE_INFO = Avram::DatabaseInfo.new(
  def self.run_database_validations!
    DATABASE_VALIDATIONS.each do |validation|
      validation.new(self, database.database_info).validate!
    end
  end
end

class Avram::Database
  memoize def self.database_info
    ..
  end
end

class Avram::DatabaseInfo
  has many DatabaseTable
end

...etc
```

**Comment by jwoertink** [comment]
The sounds like a pretty good direction. Since I've never actually been able to use the SchemaEnforcer, I'm not sure how it works now. I just have a few points I think this would need to know about, so maybe you can add these in to your thoughts on the structure:

* Need to know if the model is using a view/materialized view
* Need to know if any columns were defined on the table that aren't defined in the model
* Need to know if any of the columns in the model have a default value, and the table has those same default values
* We may allow for configuring the schema name on a per model level in the future, so this would need to know about model level configurations (i.e. different table name, different schema if possible, etc...)
* Whatever else the schema enforcer currently does.

Also, I know postgres has a way that we can run a single SQL query (albeit pretty gnarly) to get all of this info. I'm not sure if that would make things easier or more difficult in the long run. Maybe this runs that single query once, and then does all of the checks in crystal land?

**Comment by matthewmcgarvey** [comment]
This has been accomplished. The database is only queried once for all information and there is a macro that can be overridden to configure which schema enforcer validations are run https://github.com/luckyframework/avram/blob/09ea7dd5ed93aa8607c184a7aa87178773937d0b/src/avram/model.cr#L199-L202
