### ISSUE TITLE
Undefined macro 'symbol_expected_message' if mistake in migration rollback function

### ISSUE THREAD

**Issue by Jigsik** [luckyframework/avram#507]
**Describe the bug**
I tried to run `lucky db:migrate` command with an error in migration and instead of seeing an error message what went wrong I saw a message:

`Error: undefined macro variable 'symbol_expected_message'`

**To Reproduce**

1. Create migration
2. Make error in rollback function

e.g.

```
# Invalid code
def rollback
    alter :cooperation_requests do
      remove description : String
    end
end
```

instead of

```
# Valid code
def rollback
    alter :cooperation_requests do
      remove :description
    end
end
```

3. Run `lucky db:migrate` command
3. See this error in console

```
jigs@jigs-VirtualBox:/project$ lucky db.migrate
Showing last frame. Use --error-trace for full trace.

In lib/avram/src/avram/migrator/alter_table_statement.cr:201:16

 201 | {% raise symbol_expected_message % {"remove", name} %}
                ^----------------------
Error: undefined macro variable 'symbol_expected_message'
```

**Expected behavior**
Macro should be defined and print appropriate error message in console.

**Versions (please complete the following information):**
 - Lucky version (check in shard.lock): 0.24.0
 - Crystal version (`crystal --version`): 0.35.1
 - OS: Ubuntu 20.10

**Comment by jwoertink** [comment]
Hey, good find! Looking back at this code, looks like it never worked as intended. That variable is defined [here](https://github.com/luckyframework/avram/blob/master/src/avram/migrator/alter_table_statement.cr#L178). Turns out, macro `StringLiteral` doesn't have the `%` method, and you can't call the macro level variable defined outside from inside a macro... 

Instead, the `symbol_expected_message` should become a macro method that takes 2 arguments, and just interpolate the string instead.

I've moved this issue in to Avram since the fix will need to be done in this repo.
