### ISSUE TITLE
Add a query cache

### ISSUE THREAD

**Issue by paulcsmith** [luckyframework/avram#63]

**Comment by stephendolan** [comment]
@matthewmcgarvey / @jwoertink Do y'all feel like this belongs in the framework before we can cut 1.0? I'm not familiar enough with Avram to know whether or not this is something that would be a massive breaking change, but I can say that the speed of Lucky and Postgres has made query caching less of something I'm worried about having access to in my day-to-day apps.

**Comment by jwoertink** [comment]
In theory, if done right, we shouldn't need any breaking changes to make this happen. However, last time I tried to tackle this, it required some hacking to crystal-db. Since crystal-db is a dependency of crystal-pg, it made things a bit more complicated.

I'd say lets try and keep this on for 1.0. Granted speeds haven't really been an issue, I think this would really put us in the next category level. I may take another stab here soon.
