### ISSUE TITLE
Possible issue with how the Time parsing rules work

### ISSUE THREAD

**Issue by jwoertink** [luckyframework/avram#692]
Ref: https://github.com/luckyframework/lucky/issues/1530

This will need some more investigation in to how the Time parsing stuff works with all of the different edge cases.

**Comment by swilk19** [comment]
From a brief investigation of this, it seems that the expectation is that `datetime-local` input is processed by [this](https://github.com/luckyframework/avram/blob/master/src/avram/charms/time_extensions.cr#L16) time format. I reviewed the [linked developer docs](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/datetime-local) for `datetime-local` and I don't see any examples on the page with seconds included. I am not sure if that is how it will always be, or if this behavior can vary by browser, or maybe it changed at some point, etc. 

I considered adding a new test and throwing out a PR, but plugging into the existing specs [here](https://github.com/luckyframework/avram/blob/master/spec/type_extensions/time_spec.cr#L27) fails because it doesn't parse the seconds with that format, so it would need a new test block. Plus, I can work around it with the custom `time_formats` configuration for now anyway. Just figured I'd leave a note on what I found so far

**Comment by jwoertink** [comment]
Thanks for doing that investigation, @swilk19.

**Comment by swilk19** [comment]
@jwoertink I think we can close this now since #693 was merged. Appreciate the help resolving this!!
